### ISSUE TITLE
Allow non-auth users access to public documents

### ISSUE THREAD

**Issue by fullergalway** [NERC-CEH/catalogue#1]
Non-authenticated users should probably be able to see public documents, but I was getting "Access is Denied".

Not 100% sure, but I think the change would be in PermissionService.java

Change this ```toAccess``` method from:

    public boolean toAccess(CatalogueUser user, String file, String revision, String permission) throws IOException {
        Objects.requireNonNull(user);
        Objects.requireNonNull(file);
        Objects.requireNonNull(revision);
        boolean toReturn = false;
        Permission requested = Permission.valueOf(Objects.requireNonNull(permission).toUpperCase());

        Optional<MetadataInfo> document = getMetadataInfo(file, revision);
        if (document.isPresent()) {
            MetadataInfo metadataInfo = document.get();
            toReturn =
                metadataInfo.isPubliclyViewable(requested)
                ||
                metadataInfo.canAccess(requested, user, getGroupsForUser(user));
        }
        return toReturn;
    }

to something like:

    public boolean toAccess(CatalogueUser user, String file, String revision, String permission) throws IOException {
        Objects.requireNonNull(file);
        Objects.requireNonNull(revision);
        boolean toReturn = false;
        Permission requested = Permission.valueOf(Objects.requireNonNull(permission).toUpperCase());

        Optional<MetadataInfo> document = getMetadataInfo(file, revision);
        if (document.isPresent()) {
            MetadataInfo metadataInfo = document.get();
            toReturn =
                metadataInfo.isPubliclyViewable(requested)
                ||
                (user != null && metadataInfo.canAccess(requested, user, getGroupsForUser(user)));
            }
        }
        return toReturn;
    }

**Comment by chrisjohnson1988** [comment]
Hmm. Not sure about this as public documents are accessible by users who are not authenticated. You should be able to see this in action by visiting https://catalogue.ceh.ac.uk without being logged in.

**Comment by fullergalway** [comment]
Right. may have been a comment with our security setup. Thanks.
